# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene_variants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variante',
            old_name='funcion_exonica',
            new_name='funcion',
        ),
    ]
