# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_variants', '0006_auto_20161210_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='gen',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
